Web开发/02_web_django/dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from apps.cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'),
    url(r'^update$', CartUpdateView.as_view(), name='update'),
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),
    url(r'^$', CartInfoView.as_view(), name='cart'),
]

Web开发/02_web_django/dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from apps.goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(), name='index'),
    url(r'^goods/(?P<goods_id>\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', views.ListView.as_view(), name='list'),

]

Web开发/02_web_django/dailyfresh/apps/order/urls.py
from django.conf.urls import url
from apps.order import views

urlpatterns = [
    url(r'^place$', views.OrderPlaceView.as_view(), name='place'),
    url(r'^commit$', views.OrderCommitView.as_view(), name='commit'),
    url(r'^pay$', views.OrderPayView.as_view(), name='pay'),
    url(r'^check$', views.OrderCheckView.as_view(), name='check'),
    url(r'^comment/(?P<order_id>.+)$', views.OrderCommentView.as_view(), name='comment')
]

Web开发/02_web_django/dailyfresh/apps/user/urls.py
from django.conf.urls import url

from apps.user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, UserSiteView, LogoutView

urlpatterns = [
    # url(r'^register$', views.register, name='register'),
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),
    url(r'^site$', UserSiteView.as_view(), name='site'),
    url(r'^$', UserInfoView.as_view(), name='user'),
]

Web开发/02_web_django/dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^user/', include(('user.urls', 'user'), namespace='user')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('order.urls', 'order'), namespace='order')),
    url(r'^', include(('goods.urls', 'goods'), namespace='goods')),
]

Web开发/02_web_django/dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

Web开发/02_web_django/dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django_redis import get_redis_connection

from apps.goods.models import GoodsSKU
from utils.mixin import LoginRequiredMixin

# 添加商品到购物车
# 1)请求方式，采用ajax post
# 如果涉及到数据的修改（新增，更新，删除），采用post
# 如果只涉及到数据的获取，采用get
# 2)传递参数：商品id 商品数量


# /cart/add
class CartAddView(View):

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据完整性校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        try:
            count = int(count)
        except:
            return JsonResponse({'res': 2, 'errmsg': '商品数目错误'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：添加购物车记录
        # 先尝试获取sku_id的值
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 如果不存在，返回none
        cart_count = con.hget(cart_key, sku_id)
        if cart_key:
            # 累加
            if cart_count:  # 不为空
                count += int(cart_count)

        # 校验库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置hash中sku_id对应的值
        con.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的条目数
        total_count = con.hlen(cart_key)
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


class CartInfoView(LoginRequiredMixin, View):
    """购物车页面显示"""
    def get(self, request):
        user = request.user
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = con.hgetall(cart_key)

        skus = list()
        total_count = 0
        total_amount = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            # 给sku动态增加小计和数量属性
            sku.count = int(count)
            amount = int(count) * sku.price
            sku.amount = amount
            skus.append(sku)

            total_count += int(count)
            total_amount += amount

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount
        }
        return render(request, 'cart.html', context)


class CartUpdateView(View):

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据完整性校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        try:
            count = int(count)
        except:
            return JsonResponse({'res': 2, 'errmsg': '商品数目错误'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        con.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        vals = con.hvals(cart_key)
        total_count = sum(list(map(int, vals)))

        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


class CartDeleteView(View):
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        sku_id = request.POST.get('sku_id')

        # 数据完整性校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        con.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数
        vals = con.hvals(cart_key)
        total_count = sum(list(map(int, vals)))

        return JsonResponse({'res': 3,  'total_count': total_count, 'message': '删除成功'})

Web开发/02_web_django/dailyfresh/templates/base.html
{#首页 注册 登录#}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
		    </form>
        </div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{% block body %}
{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block bottom %}{% endblock bottom %}
    {% block bottomfiles %} {% endblock bottomfiles %}
</body>
</html>

Web开发/02_web_django/dailyfresh/templates/base_no_car.html
{#购物车 提交订单#}
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}

Web开发/02_web_django/dailyfresh/templates/base_user_center.html
{#用户中心3页面#}
{% extends 'base_no_car.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:site' %}" {% if page == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

Web开发/02_web_django/dailyfresh/templates/cart.html
{% extends 'base_no_car.html' %}
{% load staticfiles %}
{% block title %}
天天生鲜-购物车
{% endblock %}
{% block page_title %}
购物车
{% endblock %}
{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="post" action="{% url 'order:place' %}">
    {% for sku in skus %}
    <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
		<li class="col02"><img src="/static/media/{{ sku.image }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
                {% csrf_token %}
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_amount }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock %}
{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        // 计算被选中的商品的总件数和总价格
        function update_page_info() {
            // 获取所有被选中的商品的checkbox
            // 获取所有被选中的商品所在的ul元素
            total_count = 0;
            total_price = 0;
            $('.cart_list_td').find(':checked').parents('ul').each(function () {
            // 获取商品的数目和小计
            count = $(this).find('.num_show').val();
            amount = $(this).children('.col07').text();
            // 累加计算商品的总件数和总价格
            total_count += parseInt(count);
            total_price += parseInt(amount);
            });
            // 设置被选中的商品的总件数和总价格
            $('.settlements').find('em').text(total_price.toFixed(2));
            $('.settlements').find('b').text(total_count);
        }

        // 更新小计
        function update_goods_amount(sku_ul){
            count = sku_ul.find('.num_show').val();
            price = sku_ul.children('.col05').text();
            amount = parseInt(count) * parseFloat(price);
            // 设置小计
            sku_ul.children('.col07').text(amount.toFixed(2)+'元');
        }

        // 更新购物车中商品的数量
        update_flag = true;  // 更新是否成功标记
        total = 0;
        function update_remote_cart_info(sku_id, count){
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrf
            };
            // 设置ajax请求为同步
            $.ajaxSettings.async = false;
            $.post('/cart/update', params, function (data) {
                if (data.res == 5){
                    update_flag = true;
                    total = data.total_count;
                }
                else{
                    alert(data.errmsg);
                    update_flag = false;
                }
            });
            $.ajaxSettings.async = true;
        }

        // 商品的全选和全不选
        $('.settlements').find(':checkbox').change(function () {
            // 获取全选的状态
            is_checked = $(this).prop('checked');
            // 遍历商品的对应的checkbox
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked', is_checked)
            });
            // 更新页面的信息
            update_page_info();
        });

        // 商品对应的checkbox状态发生改变时，设置全选checkbox的状态
        $('.cart_list_td').find(':checkbox').change(function () {
            // 获取页面上所有被选中的商品的数目
            all_len = $('.cart_list_td').length;
            // 获取页面上被选中的商品的数目
            checked_len = $('.cart_list_td').find(':checked').length;
            if (checked_len < all_len){
                $('.settlements').find(':checkbox').prop('checked', false)
            }
            else{
                $('.settlements').find(':checkbox').prop('checked', true)
            }
            // 更新页面的信息
            update_page_info();
        });

        // 购物车商品数量的增加
        $('.add').click(function () {
            sku_id = $(this).next().attr('sku_id');
            count = parseInt($(this).next().val()) + 1;

            // 跟新购物车记录
            update_remote_cart_info(sku_id, count);

            // 如果更新成功
            if (update_flag){
                // 重新设置商品的数目
                $(this).next().val(count);
                // 更新小计
                update_goods_amount($(this).parents('ul'));
                // 更新总价和总件数
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked){
                    update_page_info();
                }
                // 更新页面上购物车商品的总件数
                $('.total_count').children('em').text(total)
            }
        });

        // 购物车商品数量的减少
        $('.minus').click(function () {
            sku_id = $(this).prev().attr('sku_id');
            count = parseInt($(this).prev().val()) - 1;
            if (count <= 0){
                return;
            }

            // 更新购物车记录
            update_remote_cart_info(sku_id, count);

            // 如果更新成功
            if (update_flag){
                // 重新设置商品的数目
                $(this).prev().val(count);
                // 更新小计
                update_goods_amount($(this).parents('ul'));
                // 更新总价和总件数
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked){
                    update_page_info();
                }
                // 更新页面上购物车商品的总件数
                $('.total_count').children('em').text(total)
            }
        })

        // 记录用户更新前的商品的数量
        pre_count = 0;
        $('.num_show').focus(function () {
            pre_count = $(this).val();
        });

        // 手动输入购物车商品数量
        $('.num_show').blur(function () {
            sku_id = $(this).attr('sku_id');
            count = $(this).val();

            // 校验参数
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) <= 0){
                $(this).val(pre_count);
                return;
            }

            // 跟新购物车记录
            update_remote_cart_info(sku_id, parseInt(count));

            // 如果更新成功
            if (update_flag){
                // 重新设置商品的数目
                $(this).val(count);
                // 更新小计
                update_goods_amount($(this).parents('ul'));
                // 更新总价和总件数
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked){
                    update_page_info();
                }
                // 更新页面上购物车商品的总件数
                $('.total_count').children('em').text(total)
            }
            else{
                $(this).val(pre_count);
            }
        });

        // 删除购物车商品
        $('.cart_list_td').children('.col08').children('a').click(function () {
            sku_id = $(this).parents('ul').find('.num_show').attr('sku_id');
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params = {
                'sku_id': sku_id,
                'csrfmiddlewaretoken': csrf
            };
            sku_ul = $(this).parents('ul');
            $.post('/cart/delete', params, function (data) {
                if (data.res == 3){
                    sku_ul.remove();
                    // 更新已选总价格和总件数
                    is_checked = sku_ul.find(':checkbox').prop('checked');
                    if (is_checked){
                        update_page_info()
                    }
                    // 更新总件数
                    $('.total_count').children('em').text(data.total_count)
                }
                else{
                    alert(data.errmsg);
                }
            })
        })

    </script>
{% endblock %}

Web开发/02_web_django/dailyfresh/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
天天生鲜-首页
{% endblock %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="/static/media/{{ banner.image }}" alt="幻灯片"></a></li>
				{% endfor %}

			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
                <a href="{{ banner.url }}"><img src="/static/media/{{ banner.image }}"></a>
            {% endfor %}

        </div>
	</div>
    {% for type in types %}
        	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
                    <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/media/{{ type.image }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
                    <li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="/static/media/{{ banner.sku.image }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

    {% endfor %}
{% endblock %}

Web开发/02_web_django/dailyfresh/templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}
天天生鲜-列表页
{% endblock %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="/static/media/{{ sku.image }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=sales" {% if sort == 'sales' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
                    <li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="/static/media/{{ sku.image }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
                	<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for page in pages %}
                {% if page == skus_page.number %}
                    <a href="{% url 'goods:list' type.id page %}?sort={{ sort }}" class="active">{{ page }}</a>
                {% else %}
                    <a href="{% url 'goods:list' type.id page %}?sort={{ sort }}">{{ page }}</a>
                {% endif %}
                {% endfor %}
				{% if skus_page.has_next %}
                    <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

Web开发/02_web_django/dailyfresh/templates/static_base.html
{#首页 注册 登录#}
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{% block body %}
{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block bottom %}{% endblock bottom %}
    {% block bottomfiles %} {% endblock bottomfiles %}
</body>
</html>