Web开发/02_web_django/learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 实参namespace，让我们能够将learning_logs的URL同项目中的其他URL区分开来，这在项目开始扩展时很有帮助；
    path('', include(('learning_logs.urls', 'learning_logs'),  namespace='learning_logs')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

Web开发/02_web_django/learning_log/learning_logs/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    # 主页，实参name，将这个URL模式的名称指定为index，让我们能够在代码的其他地方引用它；
    # 每当需要提供到这个主页的链接时，我们都将使用这个名称，而不是编写URL；
    path('', views.index, name='index'),
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    # 特定主题的详细页面
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

Web开发/02_web_django/learning_log/users/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

Web开发/02_web_django/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """用户学习的主题"""
    # 创建一个外键实例，将每个主题关联到特定用户
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # CharField()由文本或字符组成的数据，预留空间200个字符
    text = models.CharField(max_length=200)
    # DateTimeField()记录日期和时间的数据，auto_now_add=True，自动设置成当前日期和时间
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    # 创建一个外键实例，将每个条目关联到特定的主题； on_delete=models.CASCADE级联删除
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """存储管理模型的额外信息，设置一个额外属性：让Django在需要时使用Entries来表示多个条目"""
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示：前50个字符+..."""
        return self.text[:50] + "..."

Web开发/02_web_django/learning_log/users/models.py
from django.db import models

# Create your models here.

Web开发/02_web_django/learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        """告诉Django根据哪个模型创建表单，以及在表单中包含哪些字段"""
        model = Topic  # 根据模型Topic创建一个表单

        fields = ['text']  # 该表单只包含字段text
        labels = {'text': ''}  # 不要为字段text生成标签


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        # 小部件(widgets)是一个HTML表单元素，如单行文本框、多行文本区域或下拉列表
        # 通过设置属性widgets，可覆盖Django选择的默认小部件
        # forms.Textarea，定制了字段'text'的输入小部件，将文本区域宽度设置为80，而不是默认的40
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Web开发/02_web_django/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """学习笔记的主页"""
    return render(request, 'index.html')

@login_required
def topics(request):
    """显示所有的主题"""
    # filter(owner=request.user)让Django只从数据库中获取owner属性为当前用户的信息
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    return render(request, 'topics.html', {'topics': topics})

@login_required
def topic(request, topic_id):
    """特定主题的详细页面"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    return render(request, 'topic.html', {'topic': topic, 'entries': entries})

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':  # 未提交数据：创建一个新表单
        form = TopicForm()
    else:  # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user  # 将新主题的owner属性设置为当前用户
            new_topic.save()
            # HttpResponseRedirect类在用户提交主题后重定向到网页topics
            # reverse()根据指定的URL模型确定URL，这意味着Django将在页面被请求时生成URL
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    return render(request, 'new_topic.html', {'form': form})

@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':  # 未提交数据：创建一个新表单
        form = EntryForm()
    else:  # POST提交的数据，对数据进行处理
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    return render(request, 'new_entry.html', {'topic': topic, 'form': form})

@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':  # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:  # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    return render(request, 'edit_entry.html', {'entry': entry, 'topic': topic, 'form': form})

Web开发/02_web_django/learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':  # 显示空的注册表单
        form = UserCreationForm()
    else:  # 处理填好的表单
        form = UserCreationForm(data=request.POST)

    if form.is_valid():
        new_user = form.save()
        # 让用户自动登录，再重定向到主页
        authenticate_user = authenticate(username=new_user.username, password=request.POST['password1'])
        login(request, authenticate_user)
        return HttpResponseRedirect(reverse('learning_logs:index'))
    return render(request, 'register.html', {'form': form})

Web开发/02_web_django/learning_log/learning_logs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a>-
        <a href="{% url 'learning_logs:topics' %}">Topics</a>-
        {% if user.is_authenticated %}
            Hello, {{ user.username }}.
            <a href="{% url 'users:logout' %}">log out</a>
        {% else %}
            <a href="{% url 'users:register' %}">register</a>-
            <a href="{% url 'users:login' %}">log in</a>
        {% endif %}
    </p>
    {% block content %}{% endblock content %}
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑既有条目</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

        <p>edit entry</p>
        <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">save changes</button>
        </form>
    {% endblock content%}
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
        <p>Learning Log help you keep track of your learning, for any topic you're learning about.</p>
    {% endblock content %}
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
    <p>Learning Log</p>
    <p>Learning Log help you keep track of your learning, for any topic you're learning about.</p>
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新条目</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

        <p>Add a new entry</p>
        <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">add entry</button>
        </form>
    {% endblock content%}
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新主题</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <p>Add a new topic</p>
        <form action="{% url 'learning_logs:new_topic' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">add topic</button>
        </form>
    {% endblock content%}
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>特定主题</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <p>Topic: {{ topic }}</p>
        <p>Entries:</p>
        <p>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
        </p>
        <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
                <p>
                    <a href="{% url 'learning_logs:edit_entry' entry.id%}">edit entry</a>
                </p>
            </li>
        {% empty %}
            <li>
                There are no entries for this topic yet.
            </li>
        {% endfor %}
        </ul>
    {% endblock content %}
</body>
</html>

Web开发/02_web_django/learning_log/learning_logs/templates/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>所有主题</title>
</head>
<body>
    {% extends "base.html" %}
    {% block content %}
        <p>Topics</p>
        <ul>
            {% for topic in topics %}
                <li>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </li>
            {% empty %}
                <li>No topics have been added yet.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
    {% endblock content %}
</body>
</html>

Web开发/02_web_django/learning_log/users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">log in</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
        </form>
    {% endblock content %}
</body>
</html>

Web开发/02_web_django/learning_log/users/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">log in</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
        </form>
    {% endblock content %}
</body>
</html>